language: ruby
script: "bundle exec rake spec"
notifications:
  email:
    recipients:
      - engineering@internal.site5.com
    on_success: never
    on_failure: always
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
