language: ruby
script: "bundle exec rake spec"
notifications:
  email:
    recipients:
      - softwaredev-notify@wwwh.com
    on_success: never
    on_failure: always
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
