language: ruby
script: "bundle exec rake spec"
notifications:
  email:
    recipients:
      - dev@pressed.net
    on_success: never
    on_failure: always
rvm:
  - 2.0
  - 2.1
  - 2.2
before_install:
  - gem install bundler
